<?php
error_reporting(0);
date_default_timezone_set('America/Argentina/Jujuy');
$hosting = 'localhost';
$basededatos = 'ilcamaleonte';
$usuariobd = 'root';
$passbd = '';
$app_folder = 'app';
$assets_folder = 'assets';
$url_site = 'http://192.168.100.133/cafe/';
$sal = 'PKAN1lbMKlCc06K';
$port = '3306';
define('SELF', pathinfo(__FILE__, PATHINFO_BASENAME));
define('BASEPATH', $app_folder);
define('ASSETSPATH', $assets_folder);
define('URLSITE', $url_site);
define('HOSTINGDB', $hosting);
define('DATABASENAME', $basededatos);
define('USERDATABASE', $usuariobd);
define('PASSDATABASE', $passbd);
define('PORTDATABASE', $port);
define('SALT', $sal);
define('LOCALINS', false);
require_once BASEPATH.'/autoload.php';
